@startuml 登录设计-自动机图

[*] --> 登录流程 : 启动应用

state 登录流程 {
    [*] --> 登录界面

    state 登录界面 {
        [*] --> 输入用户名密码
        输入用户名密码 --> 登录成功 : 验证通过
        输入用户名密码 --> 登录失败 : 验证失败
        输入用户名密码 --> 注册 : 点击注册
        输入用户名密码 --> 找回密码 : 点击找回密码

        登录成功 --> 登录流程 : 进入控制面板
        登录失败 --> 输入用户名密码 : 返回登录界面
        注册 --> 注册界面 : 进入注册界面
        找回密码 --> 找回密码界面 : 进入找回密码界面
    }

    state 注册界面 {
        [*] --> 输入注册信息
        输入注册信息 --> 邮箱验证_注册界面 : 发送验证邮件
        邮箱验证_注册界面 --> 注册成功 : 验证通过
        邮箱验证_注册界面 --> 注册失败 : 验证失败
    }

    注册成功 --> 登录界面 : 返回登录界面
    注册失败 --> 输入注册信息 : 返回注册界面

    state 找回密码界面 {
        [*] --> 输入找回信息
        输入找回信息 --> 邮箱验证_找回密码界面 : 发送验证邮件
        邮箱验证_找回密码界面 --> 找回成功 : 验证通过
        邮箱验证_找回密码界面 --> 找回失败 : 验证失败
    }

    找回成功 --> 登录界面 : 返回登录界面
    找回失败 --> 输入找回信息 : 返回找回密码界面
}

登录流程 --> 主要业务流程 : 进入主要业务流程

state 主要业务流程 {
    [*] --> 主界面 : 进入主界面
    主界面 --> 好友界面 : 选择好友相关功能
    主界面 --> 群组界面 : 选择群组相关功能
    主界面 --> 用户界面 : 选择用户相关功能
    主界面 --> 查看消息界面 : 选择查看消息

    state 好友界面 {
        [*] --> 查看好友列表 : 点击查看好友列表
        [*] --> 删除好友 : 点击删除好友
        [*] --> 发送好友申请 : 点击发送好友申请
        [*] --> 验证好友申请 : 点击验证好友申请
    }

    state 群组界面 {
        [*] --> 查看群组列表 : 点击查看群组列表
        [*] --> 用户相关 : 选择用户相关功能
        [*] --> 群组相关 : 选择群组相关功能

        state 用户相关 {
            [*] --> 发送入群申请 : 点击发送入群申请
            [*] --> 验证入群申请 : 管理员审核
        }

        state 群组相关 {
            [*] --> 创建群组 : 点击创建群组
            [*] --> 解散群组 : 点击解散群组
        }
    }

    state 用户界面 {
        [*] --> 修改个人信息 : 选择修改个人信息
        修改个人信息 --> 修改敏感信息_注销账户界面 : 进入修改敏感信息界面
        修改个人信息 --> 修改非敏感信息 : 直接修改
        [*] --> 注销账户 : 选择注销账户
        [*] --> 退出登录 : 选择退出登录
        注销账户 --> 修改敏感信息_注销账户界面 : 返回登录界面
        退出登录 --> 主要业务流程 : 退出登录
    }

    state 修改敏感信息_注销账户界面 {
        [*] --> 输入敏感信息
        输入敏感信息 --> 邮箱验证_修改敏感信息界面 : 发送验证邮件
        邮箱验证_修改敏感信息界面 --> 修改成功 : 验证通过
        邮箱验证_修改敏感信息界面 --> 修改失败 : 验证失败
    }

    state 查看消息界面 {
        [*] --> 查看消息 : 查看消息
        [*] --> 发送消息 : 发送消息
        [*] --> 删除消息 : 删除消息
        [*] --> 查找消息 : 查找消息
    }

    修改成功 --> 用户界面 : 返回用户界面
    修改成功 --> 退出登录 : 注销用户后返回登录界面
    修改失败 --> 输入敏感信息 : 返回修改敏感信息界面


}

主要业务流程 --> 登录流程 : 退出登录

@enduml
