@startuml 群组连接列表声明周期

[*] --> 非活跃 : 初始化

非活跃 --> 活跃 : 用户登录\n原群组不活跃\n群组转为活跃并创建连接列表
活跃 --> 活跃 : 客户端连接断开，\n删除该列表中的连接
活跃 --> 活跃 : 用户登录\n原群组活跃\n添加连接到列表
活跃 --> 非活跃 : 客户端连接断开时检验\n群组连接列表为空，\n删除该列表,\n群组转为不活跃

@enduml
